Repository beginner0107/seoul-competition-backend, pull requests merged in 2023-04, with the labels that each got.

#3 docs: PR Template 생성
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: docs

#6 Feature/#5-Cors-설정-추가
  src/main/java/com/seoul_competition/senior_jobtraining/global/config/WebConfig.java
Labels: feature

#8 Feat/#7 swagger 설정 추가
  build.gradle
  src/main/java/com/seoul_competition/senior_jobtraining/global/config/SwaggerConfig.java
Labels: feature

#10 Feature/post관련 entity repository생성
  src/main/java/com/seoul_competition/senior_jobtraining/SeniorJobtrainingApplication.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dao/CommentRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/entity/Post.java
Labels: feature

#13 Feature/#4 공공데이터 api 가져오기
  build.gradle
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApi.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApi.java
  src/test/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApiTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApiTest.java
Labels: feature

#16 Feature/게시글 생성 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostSaveReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorCode.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ExceptionAdvice.java
Labels: feature

#17 Feature/#15 education관련 entity repository 생성
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/EducationEntity.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepositoryTest.java
Labels: feature

#18 feat: Comment Entity에 생성일, 수정일 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
Labels: feature

#19 Revert "feat: Comment Entity에 생성일, 수정일 추가"
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
Labels: bug

#25 Feature/#24 교육 목록 세부내용 조회 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApi.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApi.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepositoryTest.java
Labels: feature

#26 Feature/게시글 조회 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/response/CommentResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/entity/Post.java
Labels: feature

#27 feat: 게시글 수정, 삭제 api 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/entity/Post.java
Labels: feature

#30 Feature/#29_Education_정원_구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
Labels: feature, emergency

#31 Feature/#14 api education 매핑
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApi.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApi.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepositoryTest.java
Labels: feature

#34 feat: 댓글 생성 및 수정, 삭제 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentSaveReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorCode.java
Labels: feature

#35 Feature/#32 fifty api의 데이터 모두 가져오기
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/BusinessException.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApi.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApi.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationServiceTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApiTest.java
Labels: feature

#37 Feature/#36 교육 정보 리스트 페이지 정렬 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListResponse.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationControllerTest.java
Labels: feature

#42 Feature/게시글 페이징 기능 및 에러 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostListResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorCode.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: feature

#46 Feature/#41 교육 검색 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListPageResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationSearchListResponse.java
Labels: feature

#47 feat: Swagger 문서화를 위한 어노테이션 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
Labels: feature

#49 feat: swagger 문서 url 변경 및 CommentController에 설명 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentController.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/swagger/SwaggerRedirector.java
Labels: emergency

#51 Feature/게시글 검색 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/config/WebConfig.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: feature

#53 Feature/#52 페이지 핸들러에 검색 기능 합치기
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationSearchListResponse.java
Labels: feature

#57 fix: 게시판 페이징 기능을 수정한다.
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
Labels: feature

#61 Test: PostController 테스트 코드 작성
  src/main/resources/db/teardown.sql
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostControllerTest.java
Labels: test

#62 Feature/#58 교육 목록 요청 페이지 예외 처리
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
Labels: feature

#65 Feature/#59 교육 조회수 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
Labels: feature

#64 feat: 요청 페이지 수가 총 페이지보다 클 때 에러 처리
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
Labels: feature
