Repository beginner0107/seoul-competition-backend, pull requests merged in 2023-05, with the labels that each got.

#67 Feature/#66 review entity repository 생성
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/dao/ReviewRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/entity/Review.java
Labels: feature

#70 Feature/#69 게시글 수정 기능 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/entity/Post.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: test, feature

#72 Refactor/#71 가격 포맷팅 및 조회수 컬럼명 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepositoryTest.java
Labels: emergency, refactor

#74 Feature/#73 게시글 댓글 테스트코드 작성
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentSaveReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentUpdateReqDto.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentServiceTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostControllerTest.java
Labels: test

#76 Feature/#75 본래id 및 생성 시간 컬럼 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
Labels: feature

#79 Feature/#78 게시글 수정 api 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorCode.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: test, feature

#82 Feature/#81 게시글 댓글 수정 api 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostUpdateReqDto.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentServiceTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: test, feature

#85 Feature/#84 리뷰 수정 match check 구현 및 api 스팩 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/api/ReviewController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/application/ReviewService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/dto/request/ReviewUpdateReqDto.java
Labels: feature, refactor

#87 Feature/#80 검색 조회 기록 엔티티 생성
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserDetailRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserSearchRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/BoardCategory.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserDetail.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserSearch.java
Labels: feature

#90 chore: queryDsl 설치 및 generated(QType) 깃 무시 설정
  .gitignore
  build.gradle
Labels: chore

#92 Style/#91 교육 state 이름 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationDetailResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
Labels: style

#94 fix: 댓글 url 수정
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentController.java
Labels: fix

#98 Feature/#95 교육 컬럼 리팩토링
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/EducationSearchReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationDetailResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListPageResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/entity/Education.java
Labels: refactor

#99 Feature/#77 교육 필터링 기능 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/EducationSearchReqDto.java
Labels: feature

#101 refactor: 총 게시물 개수 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostListResponse.java
Labels: refactor

#104 feat: 쿠키 손상 시 쿠키를 만료시키는 로직 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostDetailResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/util/cookie/CookieUtil.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/util/jwt/JwtUtil.java
Labels: feature

#105 Feature/#102 교육 자동 업데이트 매핑
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationFiftyService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/convenience/EducationSeniorService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/FiftyApi.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApi.java
  src/test/java/com/seoul_competition/senior_jobtraining/global/external/openApi/education/SeniorApiTest.java
Labels: feature

#107 Feature/#106 교육 검색 db 저장
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationDetailResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationListPageResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserDetailSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserSearchSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserSearch.java
Labels: feature

#109 Fix:#108 리뷰 저장 DTO 오타 수정
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/dto/request/ReviewSaveReqDto.java
Labels: emergency, fix

#111 Feature/#110 게시글 날짜 필터링 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/request/PostSearchReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/application/ReviewService.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostServiceTest.java
Labels: test, feature, refactor

#113 Feature/#112 chat entity repository 생성
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dao/ChatHistoryRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/entity/ChatHistory.java
Labels: feature

#115 Feature/#114 chatbot 기능 구현
  build.gradle
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/api/ChatHistoryController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/application/ChatHistoryService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dto/ChatSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dto/request/ChatFeedbackReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dto/request/ChatQuestionReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dto/response/ChatAnswerResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dto/response/ChatQuestionResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/error/ErrorCode.java
Labels: feature

#117 feat: WebClient를 Bean으로 등록
  src/main/java/com/seoul_competition/senior_jobtraining/global/config/WebConfig.java
Labels: feature

#119 refactor: 챗봇 관련 api url 수정
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/api/ChatHistoryController.java
Labels: refactor

#121 Feature/#120 교육정보 추천 기능구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/OriginIdRequest.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/SearchKeywordRequest.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducation.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducations.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducationsDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducationsResponse.java
Labels: feature

#123 fix: originId -> educationId로 수정
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/EducationRequest.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/OriginIdRequest.java
Labels: fix

#125 fix: originId -> educationId로 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
Labels: fix

#127 fix: Dto의 필드명 변경 originId -> educationId
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/request/EducationRequest.java
Labels: fix

#129 Feature/#128 게시글 댓글 기능 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/dto/request/CommentUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/comment/entity/Comment.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/api/CommentControllerTest.java
  src/test/java/com/seoul_competition/senior_jobtraining/domain/comment/application/CommentServiceTest.java
Labels: refactor

#131 Feature/#130 챗봇 기록과 교육정보를 넘기는 기능을 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/dao/ChatHistoryRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/entity/ChatHistory.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/scheduler/EducationAndChatInfoScheduler.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/scheduler/dto/ChatHistoryMonthReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/scheduler/dto/EducationMonthReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/scheduler/dto/ModelUpdateData.java
Labels: feature

#135 refactor: 추천 교육목록에 price 컬럼 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducationsDto.java
Labels: refactor

#137 Fix/#136 추천교육 목록 관련 수정
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/RecommendationEducationsDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/global/scheduler/dto/ChatHistoryMonthReqDto.java
Labels: fix

#142 fix: 교육리뷰 댓글 수정 시 닉네임도 수정할 수 있게 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/application/ReviewService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/dto/request/ReviewUpdateReqDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/review/entity/Review.java
Labels: fix

#144 Refactor/#143 유저의 나이관련 `String`->`Int`로 변경
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserDetailSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserSearchSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/request/UserDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserDetail.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserSearch.java
Labels: refactor

#146 fix: 챗봇 서비스 계층에 트랜잭션 추가
  src/main/java/com/seoul_competition/senior_jobtraining/domain/chat/application/ChatHistoryService.java
Labels: fix

#147 Revert "Refactor/#143 유저의 나이관련 `Int`->`String`로 변경"
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserDetailSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/UserSearchSaveDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/request/UserDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserDetail.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/entity/UserSearch.java
Labels: refactor

#148 Feature/#140 시각화 기능 api 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/EducationRankResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/Recommend/RecommendationEducation.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/Recommend/RecommendationEducations.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/Recommend/RecommendationEducationsDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dto/response/Recommend/RecommendationEducationsResponse.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/api/PostController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostRankListResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dto/response/PostRankResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/api/UserController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/application/UserRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserDetailRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserSearchRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/response/UserSearchKeywordListResDto.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dto/response/UserSearchKeywordResDto.java
Labels: feature

#150 Refactor/#149 외부 api 초기 실행 문제 해결
  src/main/java/com/seoul_competition/senior_jobtraining/SeniorJobtrainingApplication.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/api/EducationController.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
Labels: refactor

#152 feat: 게시글 관련 더미 데이터 추가
  src/main/resources/data.sql
Labels: feature

#154 Feat:#153 시각화 모든 API의 통계 날짜를 최대 7일전으로 구현
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/application/EducationRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/education/dao/EducationRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/application/PostRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/post/dao/PostRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/application/UserRankService.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserDetailRepository.java
  src/main/java/com/seoul_competition/senior_jobtraining/domain/user/dao/UserSearchRepository.java
Labels: feature
